import { readFileSync } from 'node:fs'; import { createSign } from 'node:crypto'; import { homedir } from 'node:os';
const P='528679246';
const key=JSON.parse(readFileSync(`${homedir()}/.config/dreams-ga4/sa-key.json`,'utf8'));
const b64=o=>Buffer.from(JSON.stringify(o)).toString('base64url'); const now=Math.floor(Date.now()/1000);
const h=b64({alg:'RS256',typ:'JWT'}), c=b64({iss:key.client_email,scope:'https://www.googleapis.com/auth/analytics.readonly',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});
const sg=createSign('RSA-SHA256'); sg.update(`${h}.${c}`);
const tok=await (await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=${h}.${c}.${sg.sign(key.private_key,'base64url')}`})).json();
const H={Authorization:`Bearer ${tok.access_token}`,'Content-Type':'application/json'};
const rt=b=>fetch(`https://analyticsdata.googleapis.com/v1beta/properties/${P}:runRealtimeReport`,{method:'POST',headers:H,body:JSON.stringify(b)}).then(r=>r.json());
const a=await rt({metrics:[{name:'activeUsers'}]});
console.log('■ 실시간 활성 사용자(최근 30분):', a.rows?.[0]?.metricValues?.[0]?.value ?? 0);
const b=await rt({dimensions:[{name:'minutesAgo'}],metrics:[{name:'activeUsers'}],limit:30});
const mm={}; for(const r of b.rows||[]) mm[+r.dimensionValues[0].value]=+r.metricValues[0].value;
let line=''; for(let i=29;i>=0;i--) line+=String(mm[i]??0).padStart(2);
console.log('  분단위(29분전→지금):',line);
const c2=await rt({dimensions:[{name:'unifiedScreenName'}],metrics:[{name:'activeUsers'}],limit:10});
console.log('\n■ 실시간 조회 페이지');
for(const r of c2.rows||[]) console.log('   ',r.dimensionValues[0].value,'→',r.metricValues[0].value);
